# Displays the GitHub Sponsor button for UI SFX.
# https://docs.github.com/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository
github: [romainsimon]
